/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aevartg' at '10/24/16 10:56 AM' with Gradle 3.1
 *
 * @author aevartg, @date 10/24/16 10:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
